name: Xodium CI/CD - Docs

on:
  push:
    branches: [ main ]
    paths:
      - "src/**"
      - "Cargo.toml"
      - "Cargo.lock"
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v6.0.2

      - id: setup_rust
        name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@d197c158264056996cfba74a9c2d93886346edc3
        with:
          toolchain: stable
          target: wasm32-wasip2

      - id: build
        name: Build docs
        run: cargo doc --no-deps --target wasm32-wasip2

      - id: flatten-docs
        name: Flatten docs to root
        run: |
          cp -r target/wasm32-wasip2/doc/pumpkinplus/* target/wasm32-wasip2/doc/
          rm -rf target/wasm32-wasip2/doc/pumpkinplus

      - id: upload-artifact
        name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: target/wasm32-wasip2/doc/

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v5
